export const caseStudiesData = [
  {
    id: 1,
    categories: ["Financial"],
    image: "/assets/prudential-hero1.jpg",
    date: "2025",
    name: "Prudential Onboarding",
    category: "Financial UX",
    route: "/prudential",
  },
  {
    id: 2,
    categories: ["Healthcare"],
    image: "/assets/arthe-hero1.jpg",
    date: "2024",
    name: "Arthe",
    category: "Healthcare UX",
    route: "/arthe",
  },
  {
    id: 3,
    categories: ["Music"],
    image: "/assets/onoctave-hero1.jpg",
    date: "2024",
    name: "OnOctave",
    category: "Music Platform UX",
    route: "/onoctave",
  },
  {
    id: 4,
    categories: ["Music"],
    image: "/assets/wmg-hero1.jpg",
    date: "2023",
    name: "Warner Music Group",
    category: "Music Platform UX",
    route: "/warner-music-group",
  },
  {
    id: 5,
    categories: ["Enterprise"],
    image: "/assets/cisco-hero.jpg",
    date: "2023",
    name: "Cisco",
    category: "Enterprise UX",
    route: "/cisco",
  },
];
